/* Global dataset for demo site recipes (production-ready mock data) */
(function(){
  const data = [
    {
      id: 'creamy-tuscan-garlic-chicken',
      slug: 'creamy-tuscan-garlic-chicken',
      title: 'Creamy Tuscan Garlic Chicken',
      category: 'Dinner, Italian',
      time: '35 mins',
      servings: 4,
      difficulty: 'Easy',
      description: 'A one-pan, weeknight favorite featuring tender chicken simmered in a creamy garlic sauce with sun-dried tomatoes and spinach.',
      ingredients: [
        '4 boneless skinless chicken breasts',
        '2 tbsp olive oil',
        '4 cloves garlic, minced',
        '1 cup heavy cream',
        '1/2 cup chicken broth',
        '1/2 cup grated parmesan',
        '1/2 cup sun-dried tomatoes, chopped',
        '2 cups fresh spinach',
        '1 tsp Italian seasoning',
        'Salt and pepper to taste',
        '1 tbsp olive oil (optional)',
        '2 tbsp chopped fresh parsley',
      ],
      steps: [
        'Season chicken with salt, pepper, and Italian seasoning.',
        'Heat oil in a skillet over medium-high heat and sear chicken until browned. Remove and set aside.',
        'In the same skillet, add garlic and sauté 30 seconds until fragrant.',
        'Pour in broth and deglaze the pan, scraping up browned bits.',
        'Stir in heavy cream and parmesan; simmer until slightly thickened.',
        'Add sun-dried tomatoes and spinach; cook until spinach wilts.',
        'Return chicken to the pan and simmer until cooked through.',
        'Taste and adjust seasoning with salt and pepper.',
        'Garnish with parsley and serve over pasta or with crusty bread.',
        'Leftovers reheat well; sauce thickens slightly with time.',
      ],
      tips: [
        'Use heavy cream for a silkier sauce; half-and-half won’t thicken as much.',
        'Finish with a squeeze of lemon for brightness.',
        'Pair with a simple green salad and crusty bread.',
      ],
      nutrition: { calories: 520, protein: 34, carbs: 12, fat: 34 },
      image: 'images/recipes/creamy-tuscan-garlic-chicken.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Italian',
      rating: 4.6,
      ratingCount: 210,
      variations: ['Chicken thighs alternative', 'Creamy mushroom version'],
      storage: 'Refrigerate up to 3 days; reheat gently on the stovetop',
    },
    {
      id: 'classic-french-croissants',
      slug: 'classic-french-croissants',
      title: 'Classic French Croissants',
      category: 'Breakfast, French',
      time: '24 hours',
      servings: 12,
      difficulty: 'Hard',
      description: 'Buttery, flaky croissants with laminated dough for a bakery-worthy breakfast at home.',
      ingredients: [
        '500g all-purpose flour', '12 g salt', '60 g sugar', '7 g dry yeast', '300 ml cold water',
        '250 g unsalted butter (cold, in sheets)', 'Egg wash', 'Flour for rolling', 'Optional: chocolate or almond paste fillings'
      ],
      steps: [
        'Mix dry ingredients; add water to form dough and knead until smooth.',
        'Chill dough for 30 minutes; roll into rectangle and layer butter sheets.',
        'Fold dough into thirds; chill 30 minutes; roll and fold again; repeat 3-4 times.',
        'Roll dough into 1/8-inch thick sheet; cut triangles; roll into croissants.',
        'Proof until doubled in warm place.', 'Brush with egg wash.', 'Bake until golden brown.', 'Cool on rack.', 'Serve warm.', 'Store in airtight container for up to 2 days.'
      ],
      tips: [
        'Keep dough and butter very cold to achieve maximum lamination.',
        'Don’t rush the proofing; temperature affects fluffiness.',
        'Egg wash should be light; too much gloss can look artificial.'
      ],
      nutrition: { calories: 260, protein: 6, carbs: 28, fat: 14 },
      image: 'images/recipes/classic-french-croissants.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'French',
      rating: 4.8,
      ratingCount: 342,
      variations: ['Chocolate almond croissants'],
      storage: 'Best eaten fresh; rewarm in oven to refresh flaky layers',
    },
    {
      id: 'spicy-korean-beef-bibimbap',
      slug: 'spicy-korean-beef-bibimbap',
      title: 'Spicy Korean Beef Bibimbap',
      category: 'Dinner, Asian',
      time: '45 mins',
      servings: 4,
      difficulty: 'Medium',
      description: 'Colorful rice bowl topped with beef, vegetables, and a fried egg; a harmony of textures and flavors.',
      ingredients: [
        '2 cups cooked rice', '200 g beef, sliced', '1 cup mixed vegetables', '1 tbsp gochujang', '1 tsp sesame oil', '2 eggs', 'Garlic, ginger', 'Soy sauce', 'Green onions', 'Sesame seeds'
      ],
      steps: [
        'Marinate beef with 1 tbsp soy sauce and garlic.', 'Sauté beef until browned.','Cook vegetables until crisp-tender.','Fry eggs sunny side up.', 'Assemble rice bowls with beef, vegetables, egg.', 'Drizzle gochujang and sesame oil to taste.', 'Top with green onions and sesame seeds.', 'Serve immediately.'
      ],
      tips: [ 'Balance heat with a touch of honey or sugar.', 'Use short-grain rice for better texture.' ],
      nutrition: { calories: 520, protein: 28, carbs: 68, fat: 18 },
      image: 'images/recipes/spicy-korean-beef-bibimbap.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Korean',
      rating: 4.5,
      ratingCount: 180,
      variations: ['Chicken bibimbap', 'Vegan tofu bibimbap'],
      storage: 'Best eaten on the day; refrigerate leftovers 1 day',
    },
    {
      id: 'ultimate-chocolate-lava-cake',
      slug: 'ultimate-chocolate-lava-cake',
      title: 'Ultimate Chocolate Lava Cakes',
      category: 'Dessert',
      time: '25 mins',
      servings: 4,
      difficulty: 'Medium',
      description: 'Molten-centered chocolate cakes with a rich, gooey center and a crisp exterior.',
      ingredients: ['100 g dark chocolate', '100 g butter', '2 eggs', '2 yolks', '60 g sugar', '15 g flour', 'Pinch of salt'],
      steps: [
        'Preheat oven and grease ramekins.', 'Melt chocolate and butter together.', 'Whisk eggs, yolks, sugar.', 'Combine with cooled chocolate mixture.', 'Stir in flour and salt.', 'Pour into ramekins and bake until centers are soft.', 'Cool briefly and unmold.', 'Serve with berries or dusting of cocoa.'
      ],
      tips: [ 'Avoid overbaking to keep the center molten.', 'Chill batter for better structure.' ],
      nutrition: { calories: 420, protein: 6, carbs: 32, fat: 30 },
      image: 'images/recipes/ultimate-chocolate-lava-cake.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'French',
      rating: 4.7,
      ratingCount: 259,
      variations: ['Raspberry lava cake'],
      storage: 'Best kept warm; refrigerate leftover portions for up to 2 days',
    },
    {
      id: 'fresh-summer-gazpacho',
      slug: 'fresh-summer-gazpacho',
      title: 'Fresh Summer Gazpacho',
      category: 'Lunch, Spanish',
      time: '20 mins',
      servings: 4,
      difficulty: 'Easy',
      description: 'Chilled tomato-based soup with crisp vegetables, perfect for hot days.',
      ingredients: ['2 lbs ripe tomatoes', '1 cucumber', '1 bell pepper', '1 small onion', '2 cloves garlic', '2 tbsp olive oil', '2 tbsp red wine vinegar', 'Salt & pepper'],
      steps: [ 'Roughly chop vegetables', 'Blend until smooth; strain if desired', 'Chill until cold', 'Season and serve with croutons' ],
      tips: [ 'Roast pepper for deeper sweetness', 'Add a splash of citrus for brightness' ],
      nutrition: { calories: 150, protein: 3, carbs: 20, fat: 6 },
      image: 'images/recipes/fresh-summer-gazpacho.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Spanish',
      rating: 4.4,
      ratingCount: 132,
      variations: ['Cucumber gazpacho'],
      storage: 'Keeps well chilled for 2-3 days' 
    },
    {
      id: 'homemade-sourdough-bread',
      slug: 'homemade-sourdough-bread',
      title: 'Homemade Sourdough Bread',
      category: 'Baking',
      time: '36 hours',
      servings: 1,
      difficulty: 'Hard',
      description: 'Crusty, tangy loaf with a chewy crumb—perfect for sandwiches and toast.',
      ingredients: ['Active starter', '500 g bread flour', '350 ml water', '10 g salt'],
      steps: [
        'Feed starter and wait until bubbly', 'Autolyse flour and water', 'Add starter and salt; mix', 'Bulk ferment until doubled', 'Shape loaf', 'Proof', 'Bake with steam' ],
      tips: [ 'Scale measures for consistency', 'Score loaf before baking'],
      nutrition: { calories: 190, protein: 7, carbs: 38, fat: 2 },
      image: 'images/recipes/homemade-sourdough-bread.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Baking',
      rating: 4.9,
      ratingCount: 410,
      variations: ['Oat bread'],
      storage: 'Keeps up to 4 days in a bread box or paper bag',
    },
    {
      id: 'thai-green-curry-with-vegetables',
      slug: 'thai-green-curry-with-vegetables',
      title: 'Thai Green Curry with Vegetables',
      category: 'Dinner, Thai',
      time: '30 mins',
      servings: 4,
      difficulty: 'Easy',
      description: 'A bright, spicy curry with coconut milk and a rainbow of vegetables.',
      ingredients: ['Green curry paste', 'Coconut milk', 'Assorted vegetables', 'Fish sauce', 'Palm sugar', 'Thai basil', 'Lime'],
      steps: [ 'Sauté curry paste', 'Add coconut milk and vegetables', 'Simmer until tender', 'Finish with basil and lime' ],
      tips: [ 'Balance spice with a little sugar', 'Serve over jasmine rice' ],
      nutrition: { calories: 340, protein: 7, carbs: 24, fat: 24 },
      image: 'images/recipes/thai-green-curry-with-vegetables.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Thai',
      rating: 4.5,
      ratingCount: 95,
      variations: ['Add shrimp'],
      storage: 'Refrigerate 2-3 days; reheat gently' 
    },
    {
      id: 'classic-tiramisu',
      slug: 'classic-tiramisu',
      title: 'Classic Tiramisu',
      category: 'Dessert, Italian',
      time: '40 mins + chill',
      servings: 6,
      difficulty: 'Medium',
      description: 'A timeless Italian dessert with espresso-soaked ladyfingers and creamy mascarpone filling.',
      ingredients: ['Ladyfingers', 'Espresso', 'Mascarpone', 'Eggs', 'Sugar', 'Cocoa powder'],
      steps: [ 'Dip ladyfingers in espresso', 'Mix mascarpone with eggs and sugar', 'Layer in dish', 'Dust with cocoa and chill' ],
      tips: [ 'Eggs for safety use pasteurized eggs', 'Dust with cocoa just before serving' ],
      nutrition: { calories: 260, protein: 6, carbs: 28, fat: 14 },
      image: 'images/recipes/classic-tiramisu.svg',
      author: 'The Rustic Kitchen',
      cuisine: 'Italian',
      rating: 4.7,
      ratingCount: 280,
      variations: ['Mocha tiramisu'],
      storage: 'Chill up to 3 days' 
    }
  ];
  // attach to global SITE_DATA
  window.SITE_DATA = window.SITE_DATA || {};
  window.SITE_DATA.recipes = data;
})();
